- .github/workflows/ci.yml
- .github/workflows/rustdoc.yml
- README.md
- foundationdb-gen/Cargo.toml
- foundationdb-sys/Cargo.toml
- foundationdb/Cargo.toml
> chore: removing reference to master branch

- .github/workflows/ci.yml
- .github/workflows/cron-correctness.yml
- .github/workflows/pr-correctness.yml
- README.md
- scripts/run_bindingtester.sh
- scripts/setup_bindingtester.sh
> chore(ci): run the bindingTester every hour on Github actions

- .github/workflows/ci.yml
- foundationdb-bindingtester/src/main.rs
- scripts/run_bindingtester.sh
> Fix seed 3153055325

- foundationdb/examples/simple-index.rs
Co-authored-by: cleverakanoa <yannick.guern@clever-cloud.com>
> feat(foundationdb): Add micro index example

- foundationdb/examples/blob-with-manifest.rs
- foundationdb/examples/blob.rs
- foundationdb/src/transaction.rs
- foundationdb/tests/get.rs
> MetadataVersion

- foundationdb/README.md
- foundationdb/src/database.rs
- foundationdb/src/error.rs
- foundationdb/src/transaction.rs
- foundationdb/tests/get.rs
- foundationdb/tests/tokio.rs
> feat(foundationdb): introduce run method

- foundationdb/README.md
- foundationdb/src/database.rs
- foundationdb/src/error.rs
- foundationdb/src/transaction.rs
- foundationdb/tests/get.rs
- foundationdb/tests/tokio.rs
Reverts foundationdb-rs/foundationdb-rs#54
> Revert "feat(foundationdb): introduce run method"

- foundationdb/src/tuple/subspace.rs
Hello
The goal of this PR is to add the support of the Hash, Eq and PartialEq to Subspace.
For more details, https://github.com/foundationdb-rs/foundationdb-rs/issues/57
Thanks :)
> feat(tuple): Add Hash, Eq and PartialEq to Subspace

- README.md
See: https://github.com/badges/shields/issues/8671
> Fix GitHub workflow status badge

- flake.lock
- flake.nix
- foundationdb/examples/class-scheduling.rs
- foundationdb/src/error.rs
- foundationdb/src/transaction.rs
- foundationdb/src/tuple/element.rs
- foundationdb/tests/error.rs
> fix infinite recursion on display impl

- .github/workflows/audit.yml
- .github/workflows/ci.yml
- flake.nix
- foundationdb-bench/Cargo.toml
- foundationdb-bindingtester/Cargo.toml
- foundationdb-gen/Cargo.toml
- foundationdb-macros/Cargo.toml
- foundationdb-simulation/Cargo.toml
- foundationdb-sys/Cargo.toml
- foundationdb/Cargo.toml
> Bump dependencies

- foundationdb/src/database.rs
- foundationdb/tests/database.rs
Closes: https://github.com/foundationdb-rs/foundationdb-rs/issues/130
> feat(foundationdb): add Database.get_main_thread_busyness

- .github/workflows/ci.yml
> fix(ci): target macos-13 to avoid using M1

- foundationdb/src/error.rs
> expose FdbBindingError::get_fdb_error

- .github/workflows/release-plz.yml
- cliff.toml
- release-plz.toml
Should close #160 
Add features for `cargo publish`
> 160 fix publish by release plz

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- flake.lock
- flake.nix
- foundationdb/tests/get.rs
> 189 fix coverage ci

- .github/workflows/coverage.yml
- .github/workflows/cron-correctness.yml
- .github/workflows/pr-correctness.yml
- scripts/setup_bindingtester.sh
> Fix Python version during BindingTester

- .gitignore
- foundationdb/src/lib.rs
- foundationdb/src/timekeeper.rs
- foundationdb/tests/timekeeper.rs
This PR expose the timekeeper API resolving the issue https://github.com/foundationdb-rs/foundationdb-rs/issues/203
> feat(foundationdb) : Expose Timekeeper API

- .github/dependabot.yml
> feat(ci): configure dependabot to group PR and watch GH actions

- .github/dependabot.yml
- Cargo.lock
- foundationdb/Cargo.toml
- foundationdb/examples/key_selectors.rs
- foundationdb/src/keyselector.rs
Add examples on how to compute the right range using the KeySelector options
> Add example on range and keySelector

- .github/workflows/ci.yml
- .github/workflows/coverage.yml
- Cargo.lock
- foundationdb/Cargo.toml
- foundationdb/README.md
- foundationdb/src/database.rs
- foundationdb/src/future.rs
- foundationdb/src/transaction.rs
- foundationdb/tests/trace.rs
**Description**
This PR enables the tracing gated behind an “instrumentation” feature flag, allowing to measure transaction related operations.
> feat(foundationdb): Add optional tracing feature

- foundationdb/examples/instrumented.rs
- foundationdb/src/database.rs
- foundationdb/src/error.rs
- foundationdb/src/lib.rs
- foundationdb/src/metrics.rs
- foundationdb/src/transaction.rs
- foundationdb/tests/metrics.rs
> feat(foundationdb): Add `intrumented_run`
