CHANGELOG.md
README.md
foundationdb-bench/Cargo.toml
foundationdb-bindingtester/Cargo.toml
foundationdb-gen/Cargo.toml
foundationdb-sys/Cargo.toml
foundationdb/Cargo.toml
foundationdb/src/tuple/hca.rs
foundationdb/tests/common/mod.rs
foundationdb/tests/tokio.rs

* Bump dependencies according to [deps.rs](https://deps.rs/repo/github/foundationdb-rs/foundationdb-rs)
* Add badge
Running PR with correctness to ensure we haven't break anything during bump of deps

chore: bump deps

---

foundationdb/src/directory/directory_layer.rs
scripts/run_bindingtester.sh

This should fix #38.
More info can be found here: https://forums.foundationdb.org/t/binding-tester-set-read-version-instruction/3212/9

fix(directory): avoid initializing the version key on create_or_open

---

foundationdb/src/database.rs

This is required to create a Database from the simulation crate that we are developing.

feat(foundationdb): add raw method to create a Database

---

.github/workflows/ci.yml
.github/workflows/cron-correctness.yml
.github/workflows/pr-correctness.yml
.github/workflows/rustdoc.yml

Hopefully fixing the Coverall CI bug https://github.com/foundationdb-rs/foundationdb-rs/pull/77#issuecomment-1345556833

chore(ci): bump actions/checkout

---

.github/workflows/ci.yml
.github/workflows/cron-correctness.yml
.github/workflows/msrv.yml
.github/workflows/pr-correctness.yml
README.md
flake.nix
foundationdb-bench/Cargo.toml
foundationdb-bindingtester/Cargo.toml
foundationdb-gen/Cargo.toml
foundationdb-macros/Cargo.toml
foundationdb-sys/Cargo.toml
foundationdb/Cargo.toml
foundationdb/README.md
foundationdb/src/fdb_keys.rs
foundationdb/src/future.rs
foundationdb/src/mapped_key_values.rs

Fdb Arenas allocate structs not aligned, even though `fdb_c.h` explicitly specifies a 4bytes alignment for most of them (the others using their default alignment, 8bytes in general):
https://github.com/foundationdb-rs/foundationdb-rs/blob/e8463554a2cc5f582842bf6b27aef0db57f00456/foundationdb-sys/include/710/fdb_c.h#L88-L92
These alignment constraints are translated in Rust in bindings.rs by bindgen and exported by `foundationdb_sys`:
https://github.com/foundationdb-rs/foundationdb-rs/blob/e8463554a2cc5f582842bf6b27aef0db57f00456/foundationdb-sys/build.rs#L114-L115
```rs
#[repr(C, packed(4))]
#[derive(Debug, Copy, Clone)]
pub struct key {
pub key: *const u8,
pub key_length: ::std::os::raw::c_int,
}
pub type FDBKey = key;
```
And inherited by their "local wrappers": …

Fix alignment

---

foundationdb-bench/Cargo.toml
foundationdb-bindingtester/Cargo.toml
foundationdb-gen/Cargo.toml
foundationdb-macros/Cargo.toml
foundationdb-macros/src/lib.rs
foundationdb/Cargo.toml

This PR closes the issue https://github.com/foundationdb-rs/foundationdb-rs/issues/97
As we bump to the syn 2 major version, I've also added some unit test around the new cfg_api_versions proc_macro_attribute implementation.

97 bump dependencies

---

foundationdb-bench/Cargo.toml
foundationdb-bench/src/bin/fdb-bench.rs
foundationdb-bench/src/lib.rs

The upstream suffers from:
```
the following packages contain code that will be rejected by a future version of Rust: rustc-serialize v0.3.24
```
... which is introduced by old versioned "num" that is brought by stopwatch. Given that stopwatch is no longer maintained, we can copy its source and depend it in source form. I properly handled the LICENSE issue.

build: depend stopwatch in sources

---

foundationdb/src/tuple/mod.rs
foundationdb/src/tuple/pack.rs
foundationdb/src/tuple/subspace.rs
foundationdb/tests/tuple.rs

Adding a convenience method to support versionstamped keys within a
subpsace.
This supports any level of the subspace having incomplete versionstamps
which are merged when packing new keys and subspaces.
It keeps track of the current versionstamp alongside the prefix since
we need to know how to adjust the offsets and how many incomplete
versionstamps we have.

feat(tuple) add function to pack a subspace key with a versionstamp

---

foundationdb/src/database.rs

Hello 👋
I would like to introduce a modification in the `Database::run` parameters signature.
The function is great, but there is a little flaw with the `maybe_committed` closure parameter. As this one is a boolean which is "copiable".
Therefore, if you want to use this parameter, you have to make the closure capturing. 
```rust
db.run(|trx, maybe_committed| async move {
if maybe_committed {
// treatment
}
Ok(())
})
.await
```
But sometimes this behavior is not desired. For example, when, your closure uses an immutable reference of a variable in the outer environment.
```rust
#[derive(Debug)]
struct Data;
let data = Data;
db.run(|trx, maybe_committed| async move {
if maybe_committed {
// treatment
}
dbg!(&data)
Ok(())
})
.await
```
With the error:
```
cannot move out of `data`, a captured …
```

fix(foundationdb): make the db_run non capturing

---

.github/workflows/ci.yml
foundationdb/src/fdb_keys.rs
foundationdb/src/future.rs
foundationdb/src/lib.rs
foundationdb/src/mapped_key_values.rs

Fix std::slice::from_raw_parts usage from Nightly

---

foundationdb-simulation/build.rs
foundationdb-simulation/src/headers/ClientWorkload.h

Also this MR fixes compilation by old compilers like gcc from centos-7.

Fix foundationdb-simulation compilation with fdb-7_1 feature

---

foundationdb/examples/multi_version.rs
foundationdb/src/api.rs

Hi :wave: 
This PR brings an example of usage for the multi_version feature of FoundationDB library client. Moreover, I added a small error handling when defining the client API version to use. It will help to better understand that the installed lib version is below required rust client version.

Add multi version support example

---

Cargo.lock
Cargo.toml
foundationdb-profiling/Cargo.toml
foundationdb-profiling/src/errors.rs
foundationdb-profiling/src/lib.rs
foundationdb-profiling/src/parse.rs
foundationdb-profiling/src/parsed_key.rs
foundationdb-profiling/src/raw_transaction_profiling_block.rs
foundationdb-profiling/src/scanner.rs
foundationdb/Cargo.toml
foundationdb/src/error.rs

This PR resolves https://github.com/foundationdb-rs/foundationdb-rs/issues/204
It introduces a new crate in the workspace called `foundationdb-profiling`, the crate creation is motivated by three arguments:
- some crates pulled to achieve the task can be heavy like "async-stream"
- the profiling won't be used as daily usage but reserved to very specific tasks
- this PR only introduce the raw datablock profiling retrieving, not its actual parse, thus the crate once completed will be much larger and introduces a fuzzer to check the corectness of the parsing.
The ~~get_raw_datablocks is intentionally private because it is not intended to be the frontend of the library~~. For the same reason, the API takes read version instead of timestamp.
The …

feat(foundationdb-profiling): Profiling Keyspace Scanner

---

foundationdb-sys/build.rs
foundationdb-sys/src/lib.rs
foundationdb/src/database.rs
foundationdb/src/future.rs
foundationdb/src/lib.rs
foundationdb/src/tenant.rs
foundationdb/tests/database.rs
foundationdb/tests/get.rs
foundationdb/tests/range.rs
foundationdb/tests/tenant.rs

- use `cfg_api_versions` proc macro wherever possible
- create `if_cfg_api_versions` standard macro everywhere else
- remove `wrapper.h` in foundationdb-sys/build.rs

Simplify bindings updates

---

foundationdb-simulation/README.md
foundationdb-simulation/examples/atomic/lib.rs
foundationdb-simulation/examples/noop/lib.rs
foundationdb-simulation/src/lib.rs

Replace `ManuallyDrop<Database>` with `Arc<Database>` in `RustWorkload`.
It is both a cleaner, more "standard" type to use, and allows for runtime escaping reference detection between each phase.

Replace ManuallyDrop<Database> with Arc<Database> in RustWorkload

---

foundationdb-simulation/src/bindings.rs

**Description**
[Before](https://github.com/foundationdb-rs/foundationdb-rs/blob/02794b10c9eb75185917afd881e3f20523eb81ef/foundationdb-simulation/src/fdb_wrapper.rs#L180) reworking the public API of the simulation trace method was 
```rust
pub fn trace<S>(&self, severity: Severity, name: S, details: Vec<(String, String)>)
```
The [actual](https://github.com/foundationdb-rs/foundationdb-rs/blob/c140c81174dcced5a3c2f6f80efe008a9894ed89/foundationdb-simulation/src/bindings.rs#L103) is:
```rust
pub fn trace<S>(&self, severity: Severity, name: S, details: &[(&str, &str)])
```
This PR restores the legacy public API and extends its ability to use a mix of allocated and non allocated key/value.

fix(simulation): Recover simulation trace public api breaking change

---

foundationdb/src/transaction.rs

Error handling crates like [anyhow](https://docs.rs/anyhow/latest/anyhow/) make it easy to work with a variety of possible errors, but require that those errors implement `std::error::Error`. `TransactionCommitError` doesn't at the time of writing, but luckily `fmt::Debug` and `fmt::Display` have already been implemented for this error, so all we need to do is say it is implemented and it will be.

Implement `std::error::Error` for `TransactionCommitError`

---

.cargo/config.toml
.envrc
CONTRIBUTING.md
README.md

- Add cargo aliases for common development tasks with embedded FDB headers
- Make direnv configuration more portable by checking for nix availability
- Create comprehensive CONTRIBUTING.md with setup instructions
- Document semantic commit message conventions for clean changelogs
- Simplify README by moving contribution details to dedicated file

docs: improve contributor experience with cargo aliases and guidelines

---

foundationdb/src/database.rs

Bindgen types aren't sealed, so this function currently takes an arbitrary pointer without checking it's a pointer to a Database.

Add unsafe to new_from_pointer function

---

foundationdb/src/database.rs
foundationdb/src/transaction.rs

**Description**
This PR modify the logging behavior in case on retryable errors. The previous implementation was applying the same error level for both retryable and non-retryable errors.

fix(foundationdb): Don't log as error all commit errors
